### ISSUE TITLE
Docker and rclone?

### ISSUE THREAD

**Issue by AyaanZaveri** [bpmct/code-server-railway#52]
Is there something I can add to the Dockerfile to get Docker CLI. I tried installing it, but it wouldn't work. I'm running it code-server on Railway. Also, is there a way to mount rclone? I keep running into fuse errors that I can't fix.

Thanks!

**Comment by bpmct** [comment]
Hey. Sadly, Docker won't work in railway because railway itself is a container. The same limitations prevent rclone from being mounted. With most app platforms (Zeet, Heroku), you will also run into this.

There are a few solutions:
- you can use a VM and install these things fine :) AWS has a free tier and many cloud providers have free credit
- if you are self hosting containers, you can use [sysbox](https://github.com/nestybox/sysbox) container runtime or priviledged containers to leverage these kernel features. This is what we do for [Coder](https://coder.com/docs), our commercial product
